Oceanwater 722 detect cam fault
nasa/ow_simulator pull request #145
Opened 2021-06-22 22:47 UTC by lanseafood

## Linked Issues:
| EPIC ⚡| [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
) |
| :----------- | :----------- |
| Jira Ticket 🎟️   | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX)) |
| Github :octocat:  | # |

## Summary of Changes
* 

## Test
*

2021-06-29 00:50 UTC, kmdalal commented
I'm taking myself off this review (I think one review is enough) and prefer to review the Epic when it's ready.

2021-07-20 18:44 UTC, lanseafood commented
@Samahu ready for review

2021-07-22 20:46 UTC, scheidere reviewed
Since I am not super familiar with the code, I focused on testing. I ran the remapping and camera faults tests easily. I am having issues tracking fault statuses for the subsequent tests. I ran "roslaunch ow atacama_y1a.launch" and I can trigger cam faults using "rosrun dynamic_reconfigure dynparam set /faults camera_left_trigger_failure true" but running "rostopic echo /faults/cam_faults_status" results in a warning that that topic has not been published yet. I am not sure what I am missing, but I would be happy to test again once that becomes clear!

2021-07-27 16:28 UTC, lanseafood commented
> Since I am not super familiar with the code, I focused on testing. I ran the remapping and camera faults tests easily. I am having issues tracking fault statuses for the subsequent tests. I ran "roslaunch ow atacama_y1a.launch" and I can trigger cam faults using "rosrun dynamic_reconfigure dynparam set /faults camera_left_trigger_failure true" but running "rostopic echo /faults/cam_faults_status" results in a warning that that topic has not been published yet. I am not sure what I am missing, but I would be happy to test again once that becomes clear!

Not sure what the issue is, as I just reran and looks like the rostopic echo is working for me. Maybe try pulling again and seeing if you can see the topic. @scheidere

2021-07-27 18:35 UTC, Samahu commented
> Since I am not super familiar with the code, I focused on testing. I ran the remapping and camera faults tests easily. I am having issues tracking fault statuses for the subsequent tests. I ran "roslaunch ow atacama_y1a.launch" and I can trigger cam faults using "rosrun dynamic_reconfigure dynparam set /faults camera_left_trigger_failure true" but running "rostopic echo /faults/cam_faults_status" results in a warning that that topic has not been published yet. I am not sure what I am missing, but I would be happy to test again once that becomes clear!

I don't see this issue, I am able to monitor this topic. Did you source your `devel/setup.bash` from the terminal you ran the `rostopic echo` form?

2021-07-27 18:43 UTC, Samahu requested changes
I didn't expect the FaultDetector node to make any references to the `_original/**` topic(s). This breaks the purpose of the refactoring.

2021-07-27 18:43 UTC, Samahu commented on ow_faults_detection/src/FaultDetector.cpp
> +    10, &FaultDetector::cameraTriggerOriginalCb, this);
I didn't expect the FaultDetector node to make any references to the **_original** topic(s).

2021-07-27 18:50 UTC, Samahu commented
> I didn't expect the FaultDetector node to make any references to the `_original/**` topic(s). This breaks the purpose of the refactoring.

I do realize the reason you subscribed to the `/_original/**` but this caused me to think it wasn't probably the best way to implement camera fault this way. Rather than remapping the  `/StereoCamera/left/image_trigger` we better remap the `/StereoCamera/left/image_raw` topic.

2021-07-29 00:29 UTC, kmdalal commented
Was curious to see what up here, and I just noticed that this is in an entirely new (?) _package_ -- I had thought there would only be a new node in the ow_faults package.  The README files in both packages are identical.  @lanseafood could you please update the README.md in this package to reflect its purpose?   (unless it is updated in the target branch)

I'd like to clearly understand the difference between fault detection at this level, and fault detection in autonomy.

2021-08-02 17:45 UTC, scheidere approved these changes
I figured out my issue with running the tests. It was my own confusion with some steps in rqt. Everything runs as expected for me now.

2021-08-10 19:06 UTC, merged