fixing velocity limits in both joint_limit.yamls and lander.xarco file
nasa/ow_simulator pull request #147
Opened 2021-06-23 05:11 UTC by anjan1984

## Linked Issues:
| EPIC ⚡| [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
) |
| :----------- | :----------- |
| Jira Ticket 🎟️   | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX)) |
| Github :octocat:  | # |

## Summary of Changes
*  Updated velocity limits for all joints in both joint_limits.yaml and lander.xacro file 
* After carefully checking all the possible changes, it seems that re-timing of the trajectory is not necessary  as in branch 711. 

## Test
* Please check all the arm movements in both actions and services. 
* Test 2 and Test 9 of our Release 8.

2021-06-23 16:09 UTC, kmdalal commented
The Grind in test 2.7 was uneven -- the arm jigged and went up/down.   Revealed in the resulting trench, shown here.
![grind1](https://user-images.githubusercontent.com/9061371/123131545-a056d380-d402-11eb-93b8-f16c5718509b.png)

2021-06-23 16:13 UTC, kmdalal commented
The DigLinear in test 2.8 had good movement, but was not aligned with the trench.  See photo here.
![dig-linear](https://user-images.githubusercontent.com/9061371/123132160-43a7e880-d403-11eb-9e73-51b518a37051.png)

2021-06-23 18:18 UTC, kmdalal commented
The actions (Release test 9) all looked good!

2021-06-23 18:19 UTC, kmdalal approved these changes

2021-06-23 18:50 UTC, kmdalal commented
Please make sure there's at least one regression test (using MoveIt 1.0.7).   I used 1.0.8.

2021-06-23 23:59 UTC, AstroStucky commented
I am testing on MoveIt 1.0.7...

### Release 8 - Test 9 -  Arm Actions Test Results
All action arm movements seem to move 2-3x faster than I'm used to seeing them move before the OCEANWATER-711 bug. They also all appeared to execute their individual joint movements out of synchronicity with other joint movements, causing the scoop trajectory to be kind of random.

**grind_action_client.py** dragged the grinder along the ground, rather than moving it through it. Seen here 
![Screenshot from 2021-06-23 17-10-36](https://user-images.githubusercontent.com/17039973/123179344-6d363380-d446-11eb-88d2-42d188f9a0c1.png)

**dig_circular_action_client.py** stopped at this position
![Screenshot from 2021-06-23 17-30-15](https://user-images.githubusercontent.com/17039973/123180630-db7bf580-d448-11eb-8bce-d73accb08b0b.png)

**dig_linear_action_client.py** did something similar to dig_circular

### Arm Services Test Results
All services were called from the command line and used default arguments.
The arm services all suffered from the same fast motion and unpredictable timing of joint movements as the arm actions did. 

**/arm/guarded_move** tilted the scoop a bit before slamming it rather quickly into the ground

**/arm/grind** seemed to perform the correct grind trajectory, but did so several centimeters above the ground

**/arm/dig_circular** never made contact with the ground either, and performed the dig circular trajectory without having the scoop in the downward pointing position. See how in the screen capture of immediately after dig circular the scoop is off on tool selector joint and not even facing the right direction.
![Screenshot from 2021-06-23 17-45-48](https://user-images.githubusercontent.com/17039973/123181763-27c83500-d44b-11eb-9c61-60208bf4695e.png)

**/arm/dig_linear** was even stranger. The scoop was not pointing downwards either, and the scoop's yaw was not aligned in the direction of digging.
![Screenshot from 2021-06-23 17-51-35](https://user-images.githubusercontent.com/17039973/123181965-ab822180-d44b-11eb-88b2-b67a6e626865.png)

**/arm/deliver_sample** managed to do something like the arm delivery trajectory (but far too fast and with nonsynchronous joint movements), and then somehow wound up in this position
![Screenshot from 2021-06-23 17-53-15](https://user-images.githubusercontent.com/17039973/123182179-1f242e80-d44c-11eb-87da-0896692118e7.png)
Calling it a second time made it end in a position closer to where I'd expect, so this behavior seems to be random.

It looks as though this PR does not work if the user has MoveIt 1.0.7, but another test with 1.0.7 to verify this would be nice to see.

2021-06-24 15:43 UTC, mogumbo commented
Can anyone explain exactly what changed that made this PR necessary? Did MoveIt gain a new behavior, or did it gain a bug?

Why do joint_limits.yaml and lander.xacro have different values for velocity limits? This was also the case before this PR. Are velocity limits in one of the files ignored? Why do velocity limits need to increase so much?

2021-06-24 22:44 UTC, Samahu commented
> Can anyone explain exactly what changed that made this PR necessary? Did MoveIt gain a new behavior, or did it gain a bug?
> 
> Why do joint_limits.yaml and lander.xacro have different values for velocity limits? This was also the case before this PR. Are velocity limits in one of the files ignored? Why do velocity limits need to increase so much?

The following comment from `planning_context.launhc` describes the purpose of `joint_limits.yaml`:  
```xml
  <!-- Load updated joint limits (override information from URDF) -->
  <group ns="$(arg robot_description)_planning">
    <rosparam command="load" file="$(find ow_lander)/config/joint_limits.yaml"/>
  </group>
```

This basically sets the speeds that the planner would use when generating the trajectory. What is the net effect if the velocities specified here are higher than the ones in urdf is an open question to me. I think `joint_limits.yaml` has no effect on the simulated arm, it only affects the planner and the velocities of the generated trajectories.

2021-06-24 23:39 UTC, Samahu commented
I think I partially know what was the issue with my original hotfix #138.
When **has_velocity_limits** flag is set to true, it forces the planner to generate a trajectory that is linear in nature. When I unchecked that flag it allowed the planner to generate trajectories that has acceleration in them. We have been testing and developing with linear movement for the arm the entire time. We even optimized our PID values around this stetting.

@mogumbo To directly answer your question:
> Why do joint_limits.yaml and lander.xacro have different values for velocity limits? This was also the case before this PR. Are velocity limits in one of the files ignored? Why do velocity limits need to increase so much?

The values in the xacro files are completely overridden by joints_limits.yaml. The velocity values you specify in the xacro don't have much of an impact if you enable _has_velocity_limits_ and set a reasonable max_velocity.

This fact made me think that the issue maybe not in joint_limits itself. Rather, there could be revisions that affected how the PID  values are used in the sim and broke things.

2021-06-24 23:53 UTC, anjan1984 commented
I did try to tune the PID values with not much success.... One thing that I see different in MoveIt 1.0.8  is https://github.com/ros-planning/moveit/pull/2610... looking both in the planning and the control side of this ...

2021-06-24 23:58 UTC, Samahu commented
> I did try to tune the PID values with not much success.... One thing that I see different in MoveIt 1.0.8 is [ros-planning/moveit#2610](https://github.com/ros-planning/moveit/pull/2610)... looking both in the planning and the control side of this ...

I have noticed the moveit  2610 issue but we are not using the `pilz_industrial_motion_planner` so I don't know how it affects our simulation.

2021-06-24 23:58 UTC, Samahu commented
> > I did try to tune the PID values with not much success.... One thing that I see different in MoveIt 1.0.8 is [ros-planning/moveit#2610](https://github.com/ros-planning/moveit/pull/2610)... looking both in the planning and the control side of this ...
> 
> I have noticed the moveit 2610 issue but we are not using the `pilz_industrial_motion_planner` so I don't know how could this affected our simulation.

2021-06-28 16:40 UTC, Samahu requested changes
Please close this PR without merge in favor of PR #151 which should fix the root cause of the problem.

2021-07-01 17:00 UTC, closed without merging

2021-07-01 17:00 UTC, kmdalal commented
Replaced by new approach that was merged.