Added hint for using experimental noetic-devel branch.
nasa/ow_simulator pull request #160
Opened 2021-07-15 19:14 UTC by mogumbo

## Linked Issues:
| EPIC ⚡ | [OCEANWATER-601](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-601) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-577](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |

2021-07-15 22:43 UTC, Samahu requested changes
I think it makes sense to add the hint before the requirements and setup .. open to disputes.

2021-07-15 22:43 UTC, Samahu commented on README.md
> +    to use experimental ROS Noetic support.
The requirements page state that you need to use Ubuntu 18.04 and melodic. The note needs to proceed the requirements page in my opinion. I just moved your note one level up but consider rephrasing it to fit the new location.
```suggestion
## Getting Started
Default build instruction use ROS Melodic, but you will also find an option to use experimental ROS Noetic support.
- [Install software prerequisites](oceanwaters/doc/setup_dev_env.md)
- [Download and build OceanWATERS](oceanwaters/doc/setup_oceanwaters.md)
```

2021-07-16 17:16 UTC, kmdalal commented
> I think it makes sense to add the hint before the requirements and setup .. open to disputes.

I agree, and I think we should further and mention melodic-devel, since we're mentioning noetic-devel.

2021-07-20 16:08 UTC, mogumbo commented
> > I think it makes sense to add the hint before the requirements and setup .. open to disputes.
> 
> I agree, and I think we should further mention melodic-devel, since we're mentioning noetic-devel.

done

2021-07-20 16:59 UTC, Samahu approved these changes

2021-07-20 16:59 UTC, Samahu commented on README.md
> +Default build instruction use ROS Melodic, but you will also find an option to use experimental ROS Noetic support.
[optional] formatting, add bold or italic to highlight the ROS Distro
```suggestion
Default build instruction use _ROS Melodic_, but you will also find an option to use experimental _ROS Noetic_ support.
```

2021-07-20 17:06 UTC, kmdalal approved these changes

2021-07-20 17:19 UTC, merged