Oceanwater 852 fixed regolith spawned during grind
nasa/ow_simulator pull request #212
Opened 2021-12-23 00:06 UTC by AstroStucky

## Linked Issues:
| EPIC ⚡ | [OCEANWATER-680](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-852](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-852) |
| Github :octocat:  | # |

## Summary of Changes
* Scoop yaw now has to be at 90 deg before scoop may modify the terrain
  - Fewer unnecessary publishes to `ow_dynamic_terrain/modify_terrain_ellipse/visual` topic
  - Guarded move no longer deforms the terrain
  - Fewer sporadic visual terrain modifications, which sometimes would result in regolith being spawned during a grind operation.

## Caveat
This change does not entirely eliminate the sporadic visual terrain mods, but does reduce them. This is probably because grinding does modify the visual terrain, but in a way that rarely produces any real change to the terrain. 
@Samahu What do you think about removing the visual terrain modification call in the grinder script to ensure this no longer happens? I can't seem to notice the affects of this call in general anyways.

## Test
1. Launch whatever world you'd like.
2. Run a grind action. Ensure no regolith particles are spawned during it.
3. Run a scoop action. Ensure regolith particles are spawned during it.

2021-12-23 17:30 UTC, kmdalal commented
I will just test, @Samahu will just review code.

2021-12-23 18:48 UTC, AstroStucky commented
@Samahu elucidated how the grinder modifies terrain in discussions this morning. The modification is only noticeable when the grinder plunges far enough into the terrain. I think changing this behavior is better saved for a future PR that seeks to improve grinder terrain visual feedback. That does mean that for now deep enough grinds will cause regolith to spawn in the scoop.

2021-12-23 19:06 UTC, kmdalal commented
> That does mean that for now deep enough grinds may cause regolith to spawn in the scoop.

Is this PR still valid then?  I'll test successive grinds, each a bit deeper.

2021-12-23 19:35 UTC, kmdalal commented
Doing a default Grind with 0.05 depth, followed by another with 0.1 depth, no regolith appeared.  But when I tried with depth 0.15 (the first that visually modified the terrain), two regolith appeared in the Models list.

2021-12-23 20:14 UTC, AstroStucky commented
> > That does mean that for now deep enough grinds may cause regolith to spawn in the scoop.
> 
> Is this PR still valid then? I'll test successive grinds, each a bit deeper.

I think it is. We still benefit from restricting when the scoop can modify terrain, in particular during guarded moves.

As for eliminating unwanted regolith spawns, that's still not entirely fixed by this PR, so I suppose I should make a few more changes that address that. Thanks to you, I now know at what grind depth terrain starts getting modified at. On which world did you see modification for 0.15 depth? 

Feel free to hold-off on reviews and testing until I have a solution.

2021-12-23 20:22 UTC, kmdalal commented
> On which world did you see modification for 0.15 depth?

Atacama.  This is the only world I tested with.  Ping me when this is ready for another test!

2021-12-23 23:58 UTC, Samahu requested changes
Sorry @AstroStucky but I don't think this approach is viable. You are making the assumption that we would only scoop samples from the terrain when the scoop is parallel to the arm, which is not always the case. For example, have you thought about the **dig_circular** with _parallel_ set to `False`?

This may solve one issue for us but it breaks existing capabilities of the arm.

I don't approve this approach.

2021-12-30 21:41 UTC, AstroStucky commented
It seems I did not consider/test the parallel argument with this change. Lets discuss other solutions next week.

2021-12-30 21:41 UTC, closed without merging