Oceanwater 946 arm move joint action
nasa/ow_simulator pull request #245
Opened 2022-06-09 22:21 UTC by anjan1984

## Linked Issues:
| EPIC ⚡ | [OCEANWATER-933](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-933) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-946](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-946) |
| Github :octocat:  | # |

## Summary of Changes
* Added ros action support to command any joint to particular angle. 

## Test
* roslaunch ow atacama_y1a.launch 
terminal 2: 
to see all the option: 
./arm_move_joint_client.py -h 

./arm_move_joint_client.py 

other options: 
python3 arm_move_joint_clinet.py True 0 0.5
python3 arm_move_joint_clinet.py False 0 0.5

2022-06-10 18:02 UTC, AstroStucky commented
The test worked great! I also tested it for all joints, and angles greater than 2π.

2022-06-10 18:36 UTC, AstroStucky commented
It looks like LanderInterface.py and arm_action_servers.py are using 4-space indentation, but our Python code style calls for 2-space indention.

2022-06-10 18:40 UTC, AstroStucky commented
It looks like there are some Python scripts in ow_lander/scripts that use 2-space and some that use 4-space. I'm surprised I didn't notice this before. Fixing this should be made into a separate ticket with its own PR. For now, I'll just review this current PR as it is, with 4-space indentation.

2022-06-10 19:32 UTC, AstroStucky requested changes
Some code improvements suggested. The only suggestions I feel are required are the `choices` kwarg being added, and the name change requests, in particular for `ARM_MOVE_JOINT.action` and all related names that are auto-generated out of that.

2022-06-10 19:32 UTC, AstroStucky commented on ow_lander/scripts/arm_action_servers.py
> +class ARM_MOVE_JOINT(object):
I think we should stick to our Python class name convention.
```suggestion
class ArmMoveJoint(object):
```

2022-06-10 19:32 UTC, AstroStucky commented on ow_lander/action/ARM_MOVE_JOINT.action
> +# goal definition
We aren't adopting OWLAT's all-caps naming convention, right? The command unification document says the unified command action name should be "ArmMoveJoint", so I think this file should be named "ArmMoveJoint.action".

2022-06-10 19:32 UTC, AstroStucky commented on ow_lander/scripts/LanderInterface.py
> +class JointStateSubscriber:
Since this only provides arm joints, I think the name should reflect that.
```suggestion
class ArmJointStateSubscriber:
```

2022-06-10 19:32 UTC, AstroStucky commented on ow_lander/scripts/arm_action_servers.py
> +            joint_goal[goal.joint] = joint_goal[goal.joint] + goal.angle
[optional] I think this reads better
```suggestion
        if goal.relative:
            joint_goal[goal.joint] = joint_goal[goal.joint] + goal.angle
        else:
            joint_goal[goal.joint] = goal.angle
```

2022-06-10 19:32 UTC, AstroStucky commented on ow_lander/scripts/arm_move_joint_client.py
> +                        help='Joint index to be move 0:j_shou_yaw, 1:j_shou_pitch, 2:j_prox_pitch, 3:j_dist_pitch, 4:j_hand_yaw, 5:j_scoop_yaw', nargs='?', default=0, const=0)
You can enforce a limited set of values using the `choices` kwarg.
```suggestion
    parser.add_argument('joint', type=int,
                        help='Joint index to be moved 0:j_shou_yaw, 1:j_shou_pitch, 2:j_prox_pitch, 3:j_dist_pitch, 4:j_hand_yaw, 5:j_scoop_yaw', nargs='?', 
                        default=0, const=0, choices=range(6))
```
This lets argparse handle invalid argument checks for you.

2022-06-16 21:59 UTC, kmdalal commented on ow_lander/CMakeLists.txt
> +  FILES ARM_MOVE_JOINT.action
This needs to be `ArmMoveJoint` per our command unification document on Google Drive.

2022-06-16 22:02 UTC, kmdalal commented on ow_lander/action/ARM_MOVE_JOINT.action
> +float32[] final_angle    # joint final positions
This seems fine, though I added a comment to the unification document that we should specify the ROS type of Float32 or Float64.

2022-06-16 22:18 UTC, kmdalal commented
> It looks like there are some Python scripts in ow_lander/scripts that use 2-space and some that use 4-space. I'm surprised I didn't notice this before. Fixing this should be made into a separate ticket with its own PR. For now, I'll just review this current PR as it is, with 4-space indentation.

I agree that indentation fixes should be done separately after this work, but just do it on noetic-devel and give the files a quick test.  It's too trivial a change for a Jira or PR.

On another note, if you guys prefer 4-space indentation, we can change our guideline to that, or just remove this requirement and let programmers use their preference.  Personally, I feel that indent size should be consistent within a file, but not necessarily across files.  The more important thing is to prohibit tab characters!

2022-06-16 22:52 UTC, kmdalal commented
I'm unable to test because of the following error and crash when I start the Atacama world.  I did a clean rebuild.
```
File "/usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/arm_action_servers.py", line 13, in <module>
    from LanderInterface import JointStateSubscriber
ImportError: cannot import name 'JointStateSubscriber' from 'LanderInterface' (/usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/LanderInterface.py)
[ArmActionServers-18] process has died [pid 605800, exit code 1, cmd bash -c sleep 10.0; $0 $@ /usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/arm_action_servers.py __name:=ArmActionServers __log:=/home/kdalal/.ros/log/fe5fbe14-edc5-11ec-bf26-5f5bb02c52d1/ArmActionServers-18.log].
log file: /home/kdalal/.ros/log/fe5fbe14-edc5-11ec-bf26-5f5bb02c52d1/ArmActionServers-18*.log
```

2022-06-17 22:24 UTC, anjan1984 commented
> I'm unable to test because of the following error and crash when I start the Atacama world. I did a clean rebuild.
> 
> ```
> File "/usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/arm_action_servers.py", line 13, in <module>
>     from LanderInterface import JointStateSubscriber
> ImportError: cannot import name 'JointStateSubscriber' from 'LanderInterface' (/usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/LanderInterface.py)
> [ArmActionServers-18] process has died [pid 605800, exit code 1, cmd bash -c sleep 10.0; $0 $@ /usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/arm_action_servers.py __name:=ArmActionServers __log:=/home/kdalal/.ros/log/fe5fbe14-edc5-11ec-bf26-5f5bb02c52d1/ArmActionServers-18.log].
> log file: /home/kdalal/.ros/log/fe5fbe14-edc5-11ec-bf26-5f5bb02c52d1/ArmActionServers-18*.log
> ```

@kmdalal there was some problem with git changes from github.com and my local repo.... fixed and pushed the changes.... hope you can run it now.

2022-06-17 22:25 UTC, anjan1984 commented
Incorporated all the changes suggested

2022-06-21 13:35 UTC, kmdalal commented
Atacama seems to start fine except for the following error at the end.
```
Traceback (most recent call last):
  File "/usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/arm_action_servers.py", line 895, in <module>
    server_ArmMoveJoint = ArmMoveJoint("ArmMoveJoint")
  File "/usr/local/home/kdalal/ow/src/ow_simulator/ow_lander/scripts/arm_action_servers.py", line 804, in __init__
    self._fdbk = ow_lander.msg.ArmMoveJointFeedback()
AttributeError: module 'ow_lander.msg' has no attribute 'ArmMoveJointFeedback'
```

2022-06-22 18:07 UTC, kmdalal commented
I'm finished with testing and review, but would like to see the user documentation for this new feature as part of this Jira, mainly because the work is fresh right now and reviewers may want to test more after seeing the docs.   The documentation should include a warning that unspecified behaviors (including a "blowup" of physics as seen in the previous snapshot) can result if invalid joint angles are given.

2022-06-24 00:30 UTC, kmdalal commented on ow_lander/action/ArmMoveJoint.action
> +float32[] angle    # joint current position
The floats should be changed to float64 per our discussion with JPL today.  This is probably needed in our other action files, but we can tackle the others later, as convenient.

2022-06-24 00:34 UTC, kmdalal approved these changes
Per our discussions today, I'll approve this as is, though please start a new Jira for the user documentation ASAP, and make the float32->float64 change.  Useful new feature!

2022-06-27 18:59 UTC, AstroStucky approved these changes
Retested, and it still works. No code comments, it all looks great. This is a very nice feature to have.

2022-06-28 00:25 UTC, kmdalal commented
I've tested every arm operation repeatedly -- a single or arbitrary test is not sufficient for such a feature. While in most cases I see the behavior I'd expect, there is quite a bit of unspecified behavior, including some surprising ones such as digs happening with the side of the scoop when moving during faults.

The user documentation should be part of this work, in particular because the expected behavior isn't completely intuitive. For example, we could document (if this is the intended behavior) that if continue_arm_in_fault is false, an injected fault will always fail the operation. But when continue_arm_in_fault is true, an injected fault will not fail the operation if it is cleared before the operation finishes; otherwise the operation fails.

2022-06-28 17:44 UTC, kmdalal commented
Sorry, last comment (now deleted) was for another PR!

2022-06-28 23:46 UTC, anjan1984 commented
changed to float64 and added comments on the readme file

2022-06-28 23:46 UTC, merged