Oceanwater 968 allow arm to continue moving on arm faults
nasa/ow_simulator pull request #246
Opened 2022-06-10 19:11 UTC by anjan1984

## Linked Issues:
| EPIC ⚡ | [OCEANWATER-967](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-967) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-968](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-968) |
| Github :octocat:  | # |

## Summary of Changes
* Added option of continuing arm motion in faults

## Test
* roslaunch ow atacama_y1a.launch 
*  In a separate terminal check rosparam get /faults/continue_arm_in_fault - it should be set to false. You can change it to true using command line rosparam set /faults/continue_arm_in_fault true or using  rqt check the following box.
rqt > Dynamic Reconfigure > faults > continue_arm_in_fault
* use ros action to command any motion example ./unstow_action_client.py 
* Insert a fault using rqt 
* rqt > Dynamic Reconfigure > faults > shou_yaw_joint_locked_failure

observe the difference in behavior with stopping the arm in fault or allowing the motion.

2022-06-14 17:04 UTC, AstroStucky commented
In my testing, whether the value of `/faults/continue_arm_in_fault` is **false** or **true**, the arm will always attempt to keep moving when a fault is injected. This was the case when using both stow and unstow actions.

2022-06-14 18:54 UTC, kmdalal commented
I've been testing with just unstow/stow so far using the Continuous plan.  I consistently have the problem that @AstroStucky reported, that the arm no longer stops on a fault at all.  It completes its trajectory.   

While toggling the new parameter on and off in between operations, I occasionally see another issue: a strange extra movement of the arm during stow or unstow before it ends up at the correct location.

2022-06-14 19:09 UTC, kmdalal commented
I have not debugged, but my guess is that somehow 'continue-arm-in-fault' remains true when not intended, and when so, the arm's trajectory is altered based on which joint was faulted.  This is just a guess.

2022-06-25 01:02 UTC, anjan1984 commented
updated the branch and tested. Please review the branch again.

2022-06-27 18:32 UTC, AstroStucky commented
The test works great for me now. Great work!

2022-06-27 18:46 UTC, AstroStucky requested changes
Only minor comments and corrections, but I would really like to see a description for the new parameter that is not just a repeat of its name.

2022-06-27 18:46 UTC, AstroStucky commented on ow_lander/scripts/trajectory_async_execution.py
> +        dynamic reconfigure clinet that conncencts to faults server to get the latest state
```suggestion
        dynamic reconfigure client that connects to faults server to get the latest state
```

2022-06-27 19:03 UTC, kmdalal commented on ow_faults_injection/cfg/Faults.cfg
> +arm_faults.add("continue_arm_in_fault",       bool_t,   0, "continue arm in fault",       False)
Agreed, and a more descriptive parameter name, such as "arm_motion_continues_in_fault" (this isn't perfect but first thing that comes to mind).

2022-06-28 16:16 UTC, anjan1984 commented on ow_lander/scripts/trajectory_async_execution.py
> +        dynamic reconfigure clinet that conncencts to faults server to get the latest state
Done!

2022-06-28 16:25 UTC, anjan1984 commented on ow_faults_injection/cfg/Faults.cfg
> +arm_faults.add("continue_arm_in_fault",       bool_t,   0, "continue arm in fault",       False)
changed name to "arm_motion_continues_in_fault"

2022-06-28 16:32 UTC, anjan1984 commented
All the suggested changes have been implemented. Please re-test after a clean built

2022-06-28 17:43 UTC, kmdalal commented
Moving this here from wrong PR (!) :

I've tested every arm operation repeatedly -- a single or arbitrary test is not sufficient for such a feature. While in most cases I see the behavior I'd expect, there is quite a bit of unspecified behavior, including some surprising ones such as digs happening with the side of the scoop when moving during faults.

The user documentation should be part of this work, in particular because the expected behavior isn't completely intuitive. For example, we could document (if this is the intended behavior) that if continue_arm_in_fault is false, an injected fault will always fail the operation. But when continue_arm_in_fault is true, an injected fault will not fail the operation if it is cleared before the operation finishes; otherwise the operation fails.

2022-06-28 19:06 UTC, AstroStucky approved these changes
Thanks for the changes. Looks great!

2022-07-08 17:58 UTC, kmdalal approved these changes
The user documentation needs some work, which I'll do later.  Let's merge this as is so that Ksenia has access to it -- she may give us more feedback.  Her team has the only known need for this feature.

2022-07-08 22:02 UTC, merged