Oceanwater 996 material integrator
nasa/ow_simulator pull request #356
Opened 2023-08-17 22:11 UTC by AstroStucky

UNDER CONSTRUCTIONS

AUTHOR TODO:
1. Write PR
2. merge in noetic-devel
3. attempt sample_action.test

## Linked Issues:
| EPIC ⚡ | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
| :----------- | :----------- |
| Jira Ticket 🎟️ | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
| Github :octocat:  | # |

## Summary of Changes
* 

## Test
*

2023-08-18 19:01 UTC, AstroStucky commented
After some investigation into why sample_collect.test was failing, I concluded that the BalovnevModelPlugin is somehow having a bad reaction to the changes in this branch. It may be related to the lowered grinder/scoop modification rate. Seeing as the version of the plugin that exists in this branch is full of bugs that have already been fixed in the other branch, I have disabled it for now. 

Considering merging the other epic branch **OCEANWATER-1146_new_dig_model_integration** into this epic branch because this has reminded me that these features need to be tested together. This will all happen after this PR.

2023-08-22 21:01 UTC, mogumbo requested changes

2023-08-22 21:22 UTC, AstroStucky commented on ow_dynamic_terrain/scripts/modify_terrain_grinder_pub.py
> +    MODIFICATION_TRAVERSAL_RATE = 5.e-3
It is a rate! In space instead of time... 🤪 

Okay yea, you're right this is not a rate. MODIFICATION_DISTANCE makes sense to me

2023-08-22 21:28 UTC, AstroStucky commented on ow_materials/CMakeLists.txt
> +find_package(PCL 1.3 REQUIRED COMPONENTS
Good catch. I will add ros-noetic-pcl-ros to the getting started page

2023-08-23 20:02 UTC, AstroStucky commented on ow_materials/include/AxisAlignedGrid.tpp
> +  constexpr auto max_dimension = std::cbrt(
Say X, Y, and Z are the elements of `m_dimensions`, and `T` equals the maximum value of a `size_t`. I want to prove that
```
X <= T^(1/3)
Y <= T^(1/3)      implies      XYZ <= T       iff  X, Y, Z, T > 0
Z <= T^(1/3)
```
We can agree that the `iff` statement holds, and that means we can multiply the inequalities together one-by-one without needing to flip the symbol. 
```
XY <= T^(2/3)
Z <= T^(1/3)
```
then
```
XYZ <= T^(3/3)  = T    
```

It's really an arbitrary upper limit we're placing on the dimensions. Larger dimensions could be permitted dependent on the other values in `m_dimensions`, but at that point there is a good chance the user is accidentally making too large of a grid than they should anyways.

I'll summarize this more briefly for the comment.

2023-08-23 20:03 UTC, AstroStucky commented on ow_materials/include/AxisAlignedGrid.tpp
> +  constexpr auto max_dimension = std::cbrt(
The other option here is to allow the `size_t` to overflow, and check for the overflow to produce our error, but when I looked into overflow checking, it looked complex and messy. I liked the simplicity of this solution better.

2023-08-23 20:58 UTC, AstroStucky commented on ow_materials/include/AxisAlignedGrid.tpp
>    if (   m_dimensions.X() >= max_dimension
Fixed

2023-08-23 21:00 UTC, AstroStucky commented on ow_materials/src/MaterialDistributionPlugin.cpp
> +const string NODE_NAMES = "/ow_materials/material_distribution_plugin";
fixed

2023-08-23 22:42 UTC, AstroStucky commented on ow_materials/include/MaterialIntegrator.h
> +class MaterialIntegrator
done

2023-08-23 23:18 UTC, mogumbo approved these changes

2023-08-24 01:22 UTC, kmdalal approved these changes
Tests pass.
Light code review, mainly for style and readability -- I don't understand most of it.
Notice Rviz CPU consumption greatly increase during the 'material grid' and 'show dug' modes, but I imagine this is expected.
Very cool!

2023-08-24 16:05 UTC, merged